Onestop/Onestop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Onestop_App.urls")),
]

Onestop/Onestop_App/urls.py
from django.urls import path
from . import views
from .customDecorator import admin_required, anonymous_required, normal_user_required
from django.contrib.auth.decorators import login_required

app_name = "Onestop_App"
urlpatterns = [
    path(
        "",
        views.student_login,
        name="student_login"
    ),
    path(
        "create_query/",
        login_required(views.create_query),
        name="create_query"
    ),
    path(
        "query_status/",
        login_required(views.query_status),
        name="query_status"
    ),
    path(
        "student_timetabe/",
        login_required(views.student_timetable),
        name="student_timetable",
    ),
    path(
        "student_dashboard/",
        login_required(views.student_dashboard),
        name="student_dashboard",
    ),
    path(
        "student_logout/",
        login_required(views.student_logout),
        name="student_logout",
    ),
    path(
        "admin_dashboard/",
        admin_required(views.dashboard),
        name="dashboard"
    ),
    path(
        "admin_login/",
        anonymous_required(views.admin_login),
        name="admin_login",
    ),
    path(
        "admin_logout/",
        admin_required(views.admin_logout),
        name="admin_logout",
    ),
    path(
        "add_student/",
        admin_required(views.add_student),
        name="add_student",
    ),
    path(
        "add_faculty/",
        admin_required(views.add_faculty),
        name="add_faculty",
    ),
    path(
        "add_course/",
        admin_required(views.add_course),
        name="add_course",
    ),
    path(
        "add_section/",
        admin_required(views.add_section),
        name="add_section",
    ),
    path(
        "admin_queries/",
        admin_required(views.admin_queries),
        name="admin_queries",
    ),
    path(
        "admin_response/<int:ticket_id>/",
        admin_required(views.admin_response),
        name="admin_response",
    ),
    path(
        "chatbot/",
        login_required(views.chatbot_view),
        name="chatbot"
    ),
    path(
        "admin_notifications/",
        admin_required(views.admin_notifications),
        name="admin_notifications"
    ),
    path(
        'mark_notification_as_read/<int:notification_id>/',
        admin_required(views.mark_notification_as_read),
        name='mark_notification_as_read'
    ),
    path(
        'ticket_detail/<int:ticket_id>/',
        admin_required(views.ticket_detail), 
        name='ticket_detail'
    ),
    path(
        "student_notifications/",
        login_required(views.user_notifications),
        name="student_notifications",
    ),
    path(
        "createtimetable/",
        admin_required(views.createtimetable),
        name="createtimetable",
    ),
    path(
        'ticket_det/<int:ticket_id>/',
        login_required(views.ticket_det),
        name='ticket_det',
    ),
    path(
        'schedule_appointment/',
        login_required(views.schedule_appointment),
        name='schedule_appointment',
    ),
    path(
        'change_appointment_status/<int:appointment_id>/', 
        admin_required(views.change_appointment_status), 
        name='change_appointment_status'
    ),
    path(
        'all_appointments/', 
        admin_required(views.all_appointments), 
        name='all_appointments'
    ),
    path(
        'appointment_detail/<int:appointment_id>/', 
        admin_required(views.appointment_detail), 
        name='appointment_detail'
    ),
]

Onestop/Onestop_App/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from .forms import AdministrationLoginForm, StudentForm, FacultyForm,CourseForm,SectionForm, StudentLoginForm, TicketForm, ResponseForm,AppointmentForm,ChangeAppointmentStatusForm
from django.contrib import messages
from django import forms
from .models import Ticket, Notification, User
from .chatbot import process_begin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from .models import Appointment

# Create your views here.

def page_not_found_404(request, exception, message=None):
    return render(
        request,
        "Onestop_App/page_not_found_404.html",
        {"message": message},
        status=404,
    )
    
def student_dashboard(request):
    return render(
        request,
        "Onestop_App/student_dashboard.html",
    )

def create_query(request):
    if request.method == "POST":
        student = request.user.student  # Assuming the user is authenticated
        ticket_Form = TicketForm(request.POST, instance=Ticket(student=student))
        if ticket_Form.is_valid():
            try:
                ticket_Form.save()
                messages.success(request, "Query successfully created")
            except forms.ValidationError as e:
                messages.error(request, "Integrity Error: " + str(e))
            
            return render(
                request,
                "Onestop_App/create_query.html",
                {"ticket_Form": TicketForm(instance=Ticket(student=student))},
            )
        else:
            print(ticket_Form.errors)
            messages.error(request, "Something is not quite right (。_。)")
            return render(
                request,
                "Onestop_App/create_query.html",
                {"ticket_Form": ticket_Form},
            )
    else:
        return render(
            request,
            "Onestop_App/create_query.html",
            {"ticket_Form": TicketForm()},
        )

def query_status(request):
    student = request.user.student
    tickets = Ticket.objects.filter(student=student)
    
    return render(
        request,
        "Onestop_App/query_status.html",
        {"tickets": tickets},
    )

def student_timetable(request):
    return render(
        request,
        "Onestop_App/student_timetable.html",
    )

def dashboard(request):
    return render(
        request,
        "Onestop_App/admin_dashboard.html"
    )

def student_login(request):
    if request.method == "POST":
        login_form = StudentLoginForm(request,data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            # Attempt to sign user in
            user = authenticate(request, username=username, password=password)
            if user is not None and not user.is_superuser:
                login(request, user)
                print("hjhkj")
                return redirect("Onestop_App:student_dashboard")
            else:
                messages.error(request, "Invalid username and/or password.")
                return render(
                    request,
                    "Onestop_App/student_login.html",
                    {
                        "login_form": login_form,
                    },
                )
        else:
            messages.error(
                request, "Invalid email and/or password or submission.")
            return render(
                request,
                "Onestop_App/student_login.html",
                {"login_form": login_form},
            )
    else:
        if request.user.is_authenticated:
            return redirect("Onestop_App:student_dashboard")
        else:
            return render(
                request,
                "Onestop_App/student_login.html",
                {"login_form":StudentLoginForm()},
            )
                    
def admin_login(request):
    if request.method == "POST":
        login_form = AdministrationLoginForm(request, data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            # Attempt to sign user in
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_superuser:
                login(request, user)
                return redirect("Onestop_App:dashboard")
            else:
                messages.error(request, "Invalid username and/or password.")
                return render(
                    request,
                    "Onestop_App/admin_login.html",
                    {
                        "login_form": login_form,
                    },
                )
        else:
            messages.error(
                request, "Invalid email and/or password or submission.")
            return render(
                request,
                "Onestop_App/admin_login.html",
                {"login_form": login_form},
            )
    else:
        if request.user.is_authenticated:
            return redirect("Onestop_App:dashboard")
        else:
            return render(
                request,
                "Onestop_App/admin_login.html",
                {"login_form": AdministrationLoginForm()},
            )

def student_logout(request):
    logout(request)
    return redirect("Onestop_App:student_login")

def admin_logout(request):
    logout(request)
    return redirect("Onestop_App:admin_login")

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

def add_student(request):
    if request.method == "POST":
        student_Form = StudentForm(request.POST)
        if student_Form.is_valid():
            try:
                student = student_Form.save()
                send_student_creation_email(student)
                messages.success(
                    request, "Student profile successfully created"
                )
            except forms.ValidationError as e:
                messages.error(request, "Integrity Error " + str(e))

            return render(
                request,
                "Onestop_App/add_student.html",
                {"student_Form": StudentForm(), },
            )
        else:
            messages.error(request, "Something is not quite right (。_。)")

            return render(
                request,
                "Onestop_App/add_student.html",
                {"student_Form": student_Form, },
            )
    else:
        return render(
            request,
            "Onestop_App/add_student.html",
            {"student_Form": StudentForm(), },
        )

def send_student_creation_email(student):
    subject = 'Welcome to OneStop App'
    recipient_email = student.user.email
    context = {'username': student.user.username, 'password': student.user.password}  # Replace '*****' with the actual password

    # Pass context as the second argument to render_to_string
    html_message = render_to_string('Onestop_App/email_welcome.html', context)
    plain_message = strip_tags(html_message)

    # Send the email
    send_mail(subject, plain_message, 'digitalized.onestop@gmail.com', [recipient_email], html_message=html_message)


def add_faculty(request):
    if request.method == "POST":
        faculty_Form = FacultyForm(request.POST)
        if faculty_Form.is_valid():
            try:
                faculty_Form.save()
                messages.success(
                    request, "Faculty profile successfully created"
                )
            except forms.ValidationError as e:
                messages.error(request, "Integrity Error: " + str(e))

            return render(
                request,
                "Onestop_App/add_faculty.html",
                {"faculty_Form": FacultyForm(), },
            )
        else:
            messages.error(request, "Something is not quite right (。_。)")
            
            return render(
                request,
                "Onestop_App/add_faculty.html",
                {"faculty_Form": FacultyForm(), },
            )
    else:
        return render(
            request,
            "Onestop_App/add_faculty.html",
            {"faculty_Form": FacultyForm(),},
        )
    
def add_course(request):
    if request.method=="POST":
        course_Form = CourseForm(request.POST)
        if course_Form.is_valid():
            try:
                course_Form.save()
                messages.success(
                    request, "Course successfully created"
                )
            except forms.ValidationError as e:
                messages.error(request, "Integrity Error: " + str(e))
            
            return render(
                request,
                "Onestop_App/add_course.html",
                {"course_Form": CourseForm(), },
            )
        else:
            messages.error(request, "Something is not quite right (。_。)")
            
            return render(
                request,
                "Onestop_App/add_course.html",
                {"course_Form": CourseForm(), },
            )
    else:
        return render(
            request,
            "Onestop_App/add_course.html",
            {"course_Form": CourseForm(), },
        )
        
def add_section(request):
    if request.method=="POST":
        section_Form = SectionForm(request.POST) 
        if section_Form.is_valid():
            try:
                section_Form.save()
                messages.success(
                    request, "Section successfully created"
                )
            except forms.ValidationError as e:
                messages.error(request, "Integrity Error: " + str(e))
            

Onestop/Onestop_App/templates/Onestop_App/appointment_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Students One Stop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

    <style>
      body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
      }
      
      body.dark-mode {
        background-color: grey; /* Dark mode background color */
        color: #fff; /* Dark mode text color */
      }
      
      .sidebar {
        background-color: #333;
        padding: 20px;
        color: white;
        text-align: center;
        height: 100vh;
        width: 200px;
        position: fixed;
        z-index: 3; /* Ensure sidebar is above other content */
      }
      body.dark-mode .sidebar {
        background-color: black;
        padding: 20px;
        color: white;
        text-align: center;
        height: 100vh;
        width: 200px;
        position: fixed;
        z-index: 3; /* Ensure sidebar is above other content */
      }
      
      .sidebar a {
        display: block;
        color: white;
        text-decoration: none;
        padding: 10px 0;
      }
      
      .sidebar i {
        margin-right: 5px;
      }
      
      .content-container {
        margin-left: 220px; /* Adjusted for sidebar width */
        flex-grow: 1; /* Allow content to grow and fill remaining space */
      }
      
      .header {
        background-color: #fff;
        color: #fff;
        text-align: center;
        padding: 10px;
        position: relative;
        z-index: 1; /* Ensure header is above other content */
      }
      
      body.dark-mode .header {
        background-color: #333;
        color: black;
        text-align: center;
        padding: 10px;
        position: relative;
        z-index: 1; /* Ensure header is above other content */
      }
      
      .header img {
        max-width: 150px;
        display: block;
        margin: 0 auto; /* Center the image */
      }
      
      h1,
      h2 {
        color: #007bff;
        margin: 0;
      }
      body.dark-mode h2 {
        color: #fff; /* Text color in dark mode */
      }
      
      .logout-btn {
        background-color: #007bff;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        position: absolute;
        top: 10px;
        right: 10px;
        transition: background-color 0.3s;
      }
      
      .logout-btn:hover {
        background-color: #0056b3;
      }
      
      .content {
        max-width: 800px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      
      body.dark-mode .content {
        max-width: 800px;
        margin: 20px auto;
        background-color: black;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      
      ul {
        list-style-type: none;
        padding: 0;
      }
      
      li {
        margin-bottom: 10px;
      }
      
      .sub-heading {
        font-size: 18px;
        color: #555;
        margin-left: 10px;
        opacity: 0; /* Initially hidden */
        animation: fadeIn 10s forwards; /* Animation duration and fill-mode */
      }
      body.dark-mode .sub-heading {
        font-size: 18px;
        color: #fff;
        margin-left: 10px;
        opacity: 0; /* Initially hidden */
        animation: fadeIn 10s forwards; /* Animation duration and fill-mode */
      }
      
      .animated-word {
        font-size: 18px;
        display: inline-block;
        animation: bounce 2s infinite;
        background-image: linear-gradient(to right, #007bff, #0056b3);
        color: transparent;
        background-clip: text;
        -webkit-background-clip: text;
      }
      
      body.dark-mode .animated-word {
        font-size: 18px;
        display: inline-block;
        animation: fadeIn 2s infinite;
        background-image: linear-gradient(to right, #ffffff, #f0f0f0);
        color: transparent;
        background-clip: text;
        -webkit-background-clip: text;
      }
      
      @keyframes bounce {
        0%,
        20%,
        50%,
        80%,
        100% {
          transform: translateY(0);
        }
        40% {
          transform: translateY(-5px);
        }
        60% {
          transform: translateY(-3px);
        }
      }
      
      @keyframes fadeIn {
        to {
          opacity: 1;
        }
      }
    </style>
    <script>
      // document.addEventListener('DOMContentLoaded', function () {
      //     var options = {
      //         strings: ["Aheed, Ashad, Haseeb Present"],
      //         typeSpeed: 100,
      //         showCursor: true,
      //         cursorChar: '',
      //         onComplete: function () {
      //             function delayedFunction() {
      //                 typed.destroy();
      //             }
      //             setTimeout(delayedFunction, 2000);
      //         }
      //     };
      //     var typed = new Typed('#typed-output', options);
      // });
      
      function toggleDarkMode() {
        const body = document.body
        const darkMode = body.classList.contains('dark-mode')
        body.classList.toggle('dark-mode', !darkMode)
        localStorage.setItem('darkMode', !darkMode ? 'enabled' : 'disabled')
        setLogoImage(!darkMode)
      }
      
      function setLogoImage(isDarkMode) {
        const logoImg = document.getElementById('logo-image')
        logoImg.src = isDarkMode ? 'https://drive.google.com/uc?id=1DBXfLGIhCX7mTP782TS0u6OgAgx5jLYY' : 'https://drive.google.com/uc?id=1BKk00uxKPeyxjYbvwz9OK2LaaAAvPRes'
      }
      
      window.onload = function () {
        const darkMode = localStorage.getItem('darkMode') === 'enabled'
        document.body.classList.toggle('dark-mode', darkMode)
        setLogoImage(darkMode)
      }
    </script>
  </head>

  <body>
    <div class="sidebar">
      <a href="{% url 'Onestop_App:dashboard' %}"><i class="fas fa-home"></i>Home</a>
      <a href="{% url 'Onestop_App:add_course' %}"><i class="fas fa-plus"></i>Add Course</a>
      <a href="{% url 'Onestop_App:admin_queries' %}"><i class="fas fa-eye"></i>View Queries</a>
      <a href="{% url 'Onestop_App:createtimetable' %}"><i class="fas fa-calendar-alt"></i>Create Timetable</a>
      <a href="{% url 'Onestop_App:add_faculty' %}"><i class="fas fa-user-plus"></i>Add Faculty</a>
      <a href="{% url 'Onestop_App:add_student' %}"><i class="fas fa-user-graduate"></i>Add Students</a>
      <a href="{% url 'Onestop_App:add_section' %}"><i class="fas fa-th-list"></i>Add Sections</a>
      <a href="{% url 'Onestop_App:admin_notifications' %}"><i class="fas fa-bell"></i>View Notifications</a>
      <a href="{% url 'Onestop_App:all_appointments' %}"><i class="fas fa-calendar-check"></i>View Appointments</a>
    </div>
    <div class="content-container">
      <div class="header">
        <img id="logo-image" src="https://drive.google.com/uc?id=1BKk00uxKPeyxjYbvwz9OK2LaaAAvPRes" alt="OneStop Logo" />
        <h1 class="sub-heading"><span id="typed-output"></span></h1>
        <h1 class="sub-heading"><span class="animated-word">Digitalized</span> OneStop</h1>
        <a href="{% url 'Onestop_App:admin_logout' %}"><button class="logout-btn" type="submit">Log Out</button></a>
      </div>
      <div class="d-flex justify-content-center my-3">
        <div class="alert alert-primary" style="width: 800px;" role="alert">
          For advanced CRUD functionality, please use the <a href="/admin/">Django Admin Panel</a>.
        </div>
      </div>
    </div>
    <div class="content d-flex align-items-center flex-column">
      <h1>Appointment Detail</h1>

      <p>Appointment ID: {{ appointment.id }}</p>
      <p>Date: {{ appointment.appointment_date }}</p>
      <p>Status: {{ appointment.status }}</p>

      <!-- Add more details as needed -->

      <a href="{% url 'Onestop_App:change_appointment_status' appointment.id %}">Change Status</a>
    </div>
  </body>
</html>

Onestop/Onestop_App/templates/Onestop_App/change_appointment_status.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Students One Stop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

    <style>
      body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
      }
      
      body.dark-mode {
        background-color: grey; /* Dark mode background color */
        color: #fff; /* Dark mode text color */
      }
      
      .sidebar {
        background-color: #333;
        padding: 20px;
        color: white;
        text-align: center;
        height: 100vh;
        width: 200px;
        position: fixed;
        z-index: 3; /* Ensure sidebar is above other content */
      }
      body.dark-mode .sidebar {
        background-color: black;
        padding: 20px;
        color: white;
        text-align: center;
        height: 100vh;
        width: 200px;
        position: fixed;
        z-index: 3; /* Ensure sidebar is above other content */
      }
      
      .sidebar a {
        display: block;
        color: white;
        text-decoration: none;
        padding: 10px 0;
      }
      
      .sidebar i {
        margin-right: 5px;
      }
      
      .content-container {
        margin-left: 220px; /* Adjusted for sidebar width */
        flex-grow: 1; /* Allow content to grow and fill remaining space */
      }
      
      .header {
        background-color: #fff;
        color: #fff;
        text-align: center;
        padding: 10px;
        position: relative;
        z-index: 1; /* Ensure header is above other content */
      }
      
      body.dark-mode .header {
        background-color: #333;
        color: black;
        text-align: center;
        padding: 10px;
        position: relative;
        z-index: 1; /* Ensure header is above other content */
      }
      
      .header img {
        max-width: 150px;
        display: block;
        margin: 0 auto; /* Center the image */
      }
      
      h1,
      h2 {
        color: #007bff;
        margin: 0;
      }
      body.dark-mode h2 {
        color: #fff; /* Text color in dark mode */
      }
      
      .logout-btn {
        background-color: #007bff;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        position: absolute;
        top: 10px;
        right: 10px;
        transition: background-color 0.3s;
      }
      
      .logout-btn:hover {
        background-color: #0056b3;
      }
      
      .content {
        max-width: 800px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      
      body.dark-mode .content {
        max-width: 800px;
        margin: 20px auto;
        background-color: black;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      
      ul {
        list-style-type: none;
        padding: 0;
      }
      
      li {
        margin-bottom: 10px;
      }
      
      .sub-heading {
        font-size: 18px;
        color: #555;
        margin-left: 10px;
        opacity: 0; /* Initially hidden */
        animation: fadeIn 10s forwards; /* Animation duration and fill-mode */
      }
      body.dark-mode .sub-heading {
        font-size: 18px;
        color: #fff;
        margin-left: 10px;
        opacity: 0; /* Initially hidden */
        animation: fadeIn 10s forwards; /* Animation duration and fill-mode */
      }
      
      .animated-word {
        font-size: 18px;
        display: inline-block;
        animation: bounce 2s infinite;
        background-image: linear-gradient(to right, #007bff, #0056b3);
        color: transparent;
        background-clip: text;
        -webkit-background-clip: text;
      }
      
      body.dark-mode .animated-word {
        font-size: 18px;
        display: inline-block;
        animation: fadeIn 2s infinite;
        background-image: linear-gradient(to right, #ffffff, #f0f0f0);
        color: transparent;
        background-clip: text;
        -webkit-background-clip: text;
      }
      
      @keyframes bounce {
        0%,
        20%,
        50%,
        80%,
        100% {
          transform: translateY(0);
        }
        40% {
          transform: translateY(-5px);
        }
        60% {
          transform: translateY(-3px);
        }
      }
      
      @keyframes fadeIn {
        to {
          opacity: 1;
        }
      }
    </style>
    <script>
      // document.addEventListener('DOMContentLoaded', function () {
      //     var options = {
      //         strings: ["Aheed, Ashad, Haseeb Present"],
      //         typeSpeed: 100,
      //         showCursor: true,
      //         cursorChar: '',
      //         onComplete: function () {
      //             function delayedFunction() {
      //                 typed.destroy();
      //             }
      //             setTimeout(delayedFunction, 2000);
      //         }
      //     };
      //     var typed = new Typed('#typed-output', options);
      // });
      
      function toggleDarkMode() {
        const body = document.body
        const darkMode = body.classList.contains('dark-mode')
        body.classList.toggle('dark-mode', !darkMode)
        localStorage.setItem('darkMode', !darkMode ? 'enabled' : 'disabled')
        setLogoImage(!darkMode)
      }
      
      function setLogoImage(isDarkMode) {
        const logoImg = document.getElementById('logo-image')
        logoImg.src = isDarkMode ? 'https://drive.google.com/uc?id=1DBXfLGIhCX7mTP782TS0u6OgAgx5jLYY' : 'https://drive.google.com/uc?id=1BKk00uxKPeyxjYbvwz9OK2LaaAAvPRes'
      }
      
      window.onload = function () {
        const darkMode = localStorage.getItem('darkMode') === 'enabled'
        document.body.classList.toggle('dark-mode', darkMode)
        setLogoImage(darkMode)
      }
    </script>
  </head>

  <body>
    <div class="sidebar">
      <a href="{% url 'Onestop_App:dashboard' %}"><i class="fas fa-home"></i>Home</a>
      <a href="{% url 'Onestop_App:add_course' %}"><i class="fas fa-plus"></i>Add Course</a>
      <a href="{% url 'Onestop_App:admin_queries' %}"><i class="fas fa-eye"></i>View Queries</a>
      <a href="createtimetable.html"><i class="fas fa-calendar-alt"></i>Create Timetable</a>
      <a href="{% url 'Onestop_App:add_faculty' %}"><i class="fas fa-user-plus"></i>Add Faculty</a>
      <a href="{% url 'Onestop_App:add_student' %}"><i class="fas fa-user-graduate"></i>Add Students</a>
      <a href="{% url 'Onestop_App:add_section' %}"><i class="fas fa-th-list"></i>Add Sections</a>
      <a href="{% url 'Onestop_App:admin_notifications' %}"><i class="fas fa-bell"></i>View Notifications</a>
    </div>
    <div class="content-container">
      <div class="header">
        <img id="logo-image" src="https://drive.google.com/uc?id=1BKk00uxKPeyxjYbvwz9OK2LaaAAvPRes" alt="OneStop Logo" />
        <h1 class="sub-heading"><span id="typed-output"></span></h1>
        <h1 class="sub-heading"><span class="animated-word">Digitalized</span> OneStop</h1>
        <a href="{% url 'Onestop_App:admin_logout' %}"><button class="logout-btn" type="submit">Log Out</button></a>
      </div>
      <html lang="en">
        <body>
          <h2>Change Appointment Status</h2>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Changes</button>
          </form>
        </body>
      </html>
    </div>
  </body>
</html>